[package]
name = "time-tracker-plugin-sdk"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
description = "SDK for developing plugins for Time Tracker"

[dependencies]
serde.workspace = true
serde_json.workspace = true
